import { Property, User, Agent, Review, AreaInsight } from '@/types';

export const mockCities = [
  'Ranchi',
  'Jamshedpur',
  'Dhanbad',
  'Bokaro Steel City',
  'Deoghar',
  'Hazaribagh',
];

export const mockLocalities: Record<string, string[]> = {
  Ranchi: [
    'Doranda',
    'Main Road',
    'Kanke Road',
    'Hinoo',
    'Birsa Chowk',
    'SAIL Township',
    'Harmu',
    'Argora',
    'Namkom',
    'Ratu',
    'Kadru',
    'Booty',
    'Lalpur',
    'Hindpiri',
  ],
  Jamshedpur: [
    'Bistupur',
    'Sakchi',
    'Telco',
    'Tatanagar',
    'Adityapur',
    'MGM',
    'Baradwari',
    'Sonari',
    'Golmuri',
    'Jugsalai',
  ],
  Dhanbad: [
    'City Center',
    'Railway Station',
    'IIT Campus',
    'Dhanbad Junction',
    'Hirapur',
    'Saraidhela',
    'Dhanbad Coalfields',
  ],
  'Bokaro Steel City': ['Sector 1', 'Sector 2', 'Sector 3', 'City Center', 'Adarsh Nagar'],
  Deoghar: ['Main Road', 'Rameshwar Chowk', 'Nava Market', 'Baikunth'],
  Hazaribagh: ['Town Hall', 'Station Road', 'Charhi Road', 'Bishnugarh'],
};

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'rajan.sharma@email.com',
    phone: '9876543210',
    name: 'Rajan Sharma',
    role: 'buyer',
    aadhaarVerified: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'agent-1',
    email: 'priya.properties@email.com',
    phone: '9876543211',
    name: 'Priya Real Estate',
    role: 'agent',
    aadhaarVerified: true,
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'owner-1',
    email: 'anand.verma@email.com',
    phone: '9876543212',
    name: 'Anand Verma',
    role: 'seller',
    aadhaarVerified: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    userId: 'agent-1',
    agencyName: 'Priya Property Solutions',
    experience: 8,
    specialization: ['apartment', 'plot', 'independent_house'],
    areas: ['Ranchi', 'Hinoo', 'Kanke'],
    totalListings: 45,
    totalDeals: 120,
    rating: 4.8,
    responseTime: 15,
    verified: true,
    subscriptionTier: 'professional',
    subscriptionExpiresAt: new Date('2025-12-31'),
  },
  {
    id: 'agent-2',
    userId: 'user-2',
    agencyName: 'Jamshedpur Homes',
    experience: 12,
    specialization: ['apartment', 'villa', 'commercial'],
    areas: ['Jamshedpur', 'Bistupur', 'Sakchi'],
    totalListings: 78,
    totalDeals: 250,
    rating: 4.9,
    responseTime: 10,
    verified: true,
    subscriptionTier: 'enterprise',
    subscriptionExpiresAt: new Date('2025-12-31'),
  },
];

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    title: 'Spacious 3BHK Apartment in Doranda',
    description: 'Well-maintained 3 bedroom apartment on the 3rd floor with modern amenities. Modular kitchen, attached bathrooms, and a large balcony with park view. Society has 24/7 security, lift, and power backup.',
    type: 'apartment',
    status: 'active',
    price: 4500000,
    pricePerUnit: 4500,
    bedrooms: 3,
    bathrooms: 2,
    kitchens: 1,
    balconies: 2,
    carpetArea: 1000,
    superArea: 1250,
    address: {
      id: 'addr-1',
      city: 'Ranchi',
      locality: 'Doranda',
      landmark: 'Near Doranda College',
      pincode: '834001',
      latitude: 23.3441,
      longitude: 85.3095,
    },
    localityRating: 4.2,
    floor: 3,
    totalFloors: 5,
    propertyAge: 5,
    facing: 'east',
    possessionDate: new Date('2024-03-01'),
    ownership: 'freehold',
    media: [
      { id: 'm1', type: 'image', url: '/images/property-1-1.jpg', order: 1 },
      { id: 'm2', type: 'image', url: '/images/property-1-2.jpg', order: 2 },
      { id: 'm3', type: 'image', url: '/images/property-1-3.jpg', order: 3 },
    ],
    documents: [
      { id: 'd1', name: 'Registry Document', type: 'registry', url: '/docs/prop1-registry.pdf', verified: true, verifiedAt: new Date('2024-01-20') },
      { id: 'd2', name: 'Khata Certificate', type: 'khata', url: '/docs/prop1-khata.pdf', verified: true, verifiedAt: new Date('2024-01-20') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-1',
    agentId: 'agent-1',
    amenities: ['parking', 'lift', 'security', 'water_supply', 'power_backup', 'garden'],
    isFeatured: true,
    views: 245,
    saves: 32,
    nearSchool: true,
    nearHospital: true,
    nearRailwayStation: false,
    nearIndustrialArea: false,
    distanceToSchool: 0.5,
    distanceToHospital: 1.2,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: 'prop-2',
    title: 'Premium Plot in Kanke Road',
    description: 'Prime residential plot in a developed area with clear titles. All civic amenities available. Ideal for building your dream home. Plot has road access on two sides.',
    type: 'plot',
    status: 'active',
    price: 2500000,
    pricePerUnit: 2500,
    address: {
      id: 'addr-2',
      city: 'Ranchi',
      locality: 'Kanke Road',
      landmark: 'Near BIT Mesra',
      pincode: '835215',
      latitude: 23.3682,
      longitude: 85.3555,
    },
    plotArea: 2500,
    length: 50,
    breadth: 50,
    landType: 'residential',
    roadAccess: 'paved',
    boundaryWall: true,
    ownership: 'freehold',
    media: [
      { id: 'm4', type: 'image', url: '/images/property-2-1.jpg', order: 1 },
      { id: 'm5', type: 'image', url: '/images/property-2-2.jpg', order: 2 },
    ],
    documents: [
      { id: 'd3', name: 'Registry Document', type: 'registry', url: '/docs/prop2-registry.pdf', verified: true, verifiedAt: new Date('2024-02-01') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-2',
    amenities: ['parking', 'security'],
    isFeatured: true,
    views: 189,
    saves: 24,
    nearSchool: true,
    nearHospital: false,
    nearRailwayStation: false,
    nearIndustrialArea: false,
    distanceToSchool: 0.8,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: 'prop-3',
    title: 'Luxury 4BHK Villa in Hinoo',
    description: 'Stunning independent villa with modern architecture. Features include a private garden, rooftop terrace, modular kitchen, and smart home features. Perfect for families seeking premium living.',
    type: 'villa',
    status: 'active',
    price: 8500000,
    pricePerUnit: 5667,
    bedrooms: 4,
    bathrooms: 4,
    kitchens: 2,
    balconies: 3,
    carpetArea: 1500,
    superArea: 2000,
    plotArea: 3000,
    address: {
      id: 'addr-3',
      city: 'Ranchi',
      locality: 'Hinoo',
      landmark: 'Near Hinoo Railway Station',
      pincode: '834002',
      latitude: 23.3695,
      longitude: 85.3421,
    },
    localityRating: 4.5,
    propertyAge: 2,
    facing: 'northeast',
    ownership: 'freehold',
    media: [
      { id: 'm6', type: 'image', url: '/images/property-3-1.jpg', order: 1 },
      { id: 'm7', type: 'image', url: '/images/property-3-2.jpg', order: 2 },
      { id: 'm8', type: 'video', url: '/videos/property-3-walkthrough.mp4', order: 3 },
    ],
    documents: [
      { id: 'd4', name: 'Registry Document', type: 'registry', url: '/docs/prop3-registry.pdf', verified: true, verifiedAt: new Date('2024-01-10') },
      { id: 'd5', name: 'RERA Certificate', type: 'rera', url: '/docs/prop3-rera.pdf', verified: true, verifiedAt: new Date('2024-01-10') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-3',
    agentId: 'agent-1',
    amenities: ['parking', 'security', 'water_supply', 'power_backup', 'garden', 'air_conditioning'],
    isFeatured: false,
    views: 156,
    saves: 18,
    nearSchool: true,
    nearHospital: true,
    nearRailwayStation: true,
    nearIndustrialArea: false,
    distanceToSchool: 0.3,
    distanceToHospital: 0.8,
    distanceToRailway: 0.5,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'prop-4',
    title: 'Agricultural Land in Namkom',
    description: 'Fertile agricultural land with excellent water availability. Suitable for farming or investment. Clear titles and immediate possession available.',
    type: 'agricultural_land',
    status: 'active',
    price: 1800000,
    pricePerUnit: 180,
    plotArea: 10000,
    address: {
      id: 'addr-4',
      city: 'Ranchi',
      locality: 'Namkom',
      landmark: 'Near Namkom Railway Station',
      pincode: '834010',
      latitude: 23.3198,
      longitude: 85.2912,
    },
    landType: 'agricultural',
    roadAccess: 'kutcha',
    irrigationAvailable: true,
    ownership: 'freehold',
    media: [
      { id: 'm9', type: 'image', url: '/images/property-4-1.jpg', order: 1 },
    ],
    documents: [
      { id: 'd6', name: 'Registry Document', type: 'registry', url: '/docs/prop4-registry.pdf', verified: false },
    ],
    verificationStatus: 'pending',
    ownerId: 'owner-4',
    amenities: ['water_supply'],
    isFeatured: false,
    views: 98,
    saves: 12,
    nearSchool: false,
    nearHospital: false,
    nearRailwayStation: true,
    nearIndustrialArea: false,
    distanceToRailway: 1.5,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'prop-5',
    title: 'Modern 2BHK in Jamshedpur',
    description: 'Newly constructed 2BHK apartment with contemporary design. Located in a peaceful neighborhood with easy access to schools, hospitals, and market.',
    type: 'apartment',
    status: 'active',
    price: 3200000,
    pricePerUnit: 4000,
    bedrooms: 2,
    bathrooms: 2,
    kitchens: 1,
    balconies: 1,
    carpetArea: 800,
    superArea: 950,
    address: {
      id: 'addr-5',
      city: 'Jamshedpur',
      locality: 'Bistupur',
      landmark: 'Near Bistupur Market',
      pincode: '831001',
      latitude: 22.8027,
      longitude: 86.1785,
    },
    localityRating: 4.4,
    floor: 2,
    totalFloors: 4,
    propertyAge: 1,
    facing: 'west',
    ownership: 'freehold',
    media: [
      { id: 'm10', type: 'image', url: '/images/property-5-1.jpg', order: 1 },
      { id: 'm11', type: 'image', url: '/images/property-5-2.jpg', order: 2 },
    ],
    documents: [
      { id: 'd7', name: 'Registry Document', type: 'registry', url: '/docs/prop5-registry.pdf', verified: true, verifiedAt: new Date('2024-01-25') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-5',
    agentId: 'agent-2',
    amenities: ['parking', 'lift', 'security', 'water_supply', 'power_backup'],
    isFeatured: true,
    views: 312,
    saves: 45,
    nearSchool: true,
    nearHospital: true,
    nearRailwayStation: true,
    nearIndustrialArea: true,
    distanceToSchool: 0.4,
    distanceToHospital: 1.0,
    distanceToRailway: 0.6,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-22'),
  },
  {
    id: 'prop-6',
    title: 'Commercial Shop in Main Road',
    description: 'Prime commercial property on the main road with high footfall. Ideal for retail, clinic, or office. Wide frontage and excellent visibility.',
    type: 'commercial',
    status: 'active',
    price: 5500000,
    expectedRent: 35000,
    carpetArea: 500,
    address: {
      id: 'addr-6',
      city: 'Ranchi',
      locality: 'Main Road',
      landmark: 'Near Oberoi Hotel',
      pincode: '834001',
      latitude: 23.3561,
      longitude: 85.3178,
    },
    localityRating: 4.8,
    propertyAge: 8,
    facing: 'south',
    ownership: 'freehold',
    media: [
      { id: 'm12', type: 'image', url: '/images/property-6-1.jpg', order: 1 },
    ],
    documents: [
      { id: 'd8', name: 'Registry Document', type: 'registry', url: '/docs/prop6-registry.pdf', verified: true, verifiedAt: new Date('2024-02-10') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-6',
    amenities: ['parking', 'security', 'power_backup'],
    isFeatured: false,
    views: 178,
    saves: 14,
    nearSchool: false,
    nearHospital: true,
    nearRailwayStation: false,
    nearIndustrialArea: false,
    distanceToHospital: 0.8,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-26'),
  },
  {
    id: 'prop-7',
    title: 'Independent House in Dhanbad',
    description: 'Spacious independent house with 4 bedrooms, ideal for large families. Large compound with parking space for 3 cars. Quiet residential area with all amenities nearby.',
    type: 'independent_house',
    status: 'active',
    price: 3800000,
    pricePerUnit: 2533,
    bedrooms: 4,
    bathrooms: 3,
    kitchens: 2,
    balconies: 2,
    carpetArea: 1500,
    plotArea: 2400,
    address: {
      id: 'addr-7',
      city: 'Dhanbad',
      locality: 'City Center',
      landmark: 'Near City Center Mall',
      pincode: '826001',
      latitude: 23.7953,
      longitude: 86.4304,
    },
    localityRating: 4.0,
    propertyAge: 12,
    facing: 'east',
    ownership: 'freehold',
    media: [
      { id: 'm13', type: 'image', url: '/images/property-7-1.jpg', order: 1 },
      { id: 'm14', type: 'image', url: '/images/property-7-2.jpg', order: 2 },
    ],
    documents: [
      { id: 'd9', name: 'Registry Document', type: 'registry', url: '/docs/prop7-registry.pdf', verified: true, verifiedAt: new Date('2024-01-30') },
      { id: 'd10', name: 'Khata Certificate', type: 'khata', url: '/docs/prop7-khata.pdf', verified: true, verifiedAt: new Date('2024-01-30') },
    ],
    verificationStatus: 'verified',
    ownerId: 'owner-7',
    amenities: ['parking', 'water_supply', 'power_backup', 'garden'],
    isFeatured: false,
    views: 134,
    saves: 19,
    nearSchool: true,
    nearHospital: false,
    nearRailwayStation: true,
    nearIndustrialArea: true,
    distanceToSchool: 0.7,
    distanceToRailway: 1.0,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    id: 'prop-8',
    title: 'Budget 1BHK in Harmu',
    description: 'Affordable 1BHK apartment perfect for first-time buyers or tenants. Basic amenities included. Good location with nearby market and bus stop.',
    type: 'apartment',
    status: 'active',
    price: 1800000,
    pricePerUnit: 3000,
    bedrooms: 1,
    bathrooms: 1,
    kitchens: 1,
    carpetArea: 600,
    superArea: 700,
    address: {
      id: 'addr-8',
      city: 'Ranchi',
      locality: 'Harmu',
      landmark: 'Near Harmu Chowk',
      pincode: '834002',
      latitude: 23.3721,
      longitude: 85.3289,
    },
    localityRating: 3.8,
    floor: 1,
    totalFloors: 3,
    propertyAge: 6,
    facing: 'north',
    ownership: 'freehold',
    media: [
      { id: 'm15', type: 'image', url: '/images/property-8-1.jpg', order: 1 },
    ],
    documents: [],
    verificationStatus: 'unverified',
    ownerId: 'owner-8',
    amenities: ['parking', 'water_supply'],
    isFeatured: false,
    views: 89,
    saves: 8,
    nearSchool: true,
    nearHospital: false,
    nearRailwayStation: false,
    nearIndustrialArea: false,
    distanceToSchool: 0.5,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-28'),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    userId: 'user-1',
    locality: 'Doranda',
    rating: 4.5,
    comment: 'Good locality with all basic amenities nearby. Schools and hospitals within 1km. Market is walkable.',
    waterRating: 4,
    electricityRating: 4,
    safetyRating: 4.5,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: 'rev-2',
    userId: 'user-2',
    locality: 'Kanke Road',
    rating: 4.8,
    comment: 'Premium area with excellent connectivity. Near BIT Mesra so environment is good.',
    waterRating: 5,
    electricityRating: 4.5,
    safetyRating: 5,
    createdAt: new Date('2024-02-01'),
  },
  {
    id: 'rev-3',
    userId: 'user-3',
    locality: 'Bistupur',
    rating: 4.6,
    comment: 'Well-developed area with all facilities. Tata infrastructure ensures good quality of life.',
    waterRating: 4.5,
    electricityRating: 5,
    safetyRating: 4.5,
    createdAt: new Date('2024-01-15'),
  },
];

export const mockAreaInsights: AreaInsight[] = [
  {
    id: 'ai-1',
    locality: 'Doranda',
    city: 'Ranchi',
    propertyType: 'apartment',
    avgPrice: 4200000,
    pricePerSqFt: 4200,
    trend: 'up',
    totalListings: 45,
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'ai-2',
    locality: 'Kanke Road',
    city: 'Ranchi',
    propertyType: 'plot',
    avgPrice: 2300000,
    pricePerSqFt: 2300,
    trend: 'stable',
    totalListings: 28,
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'ai-3',
    locality: 'Bistupur',
    city: 'Jamshedpur',
    propertyType: 'apartment',
    avgPrice: 3500000,
    pricePerSqFt: 4375,
    trend: 'up',
    totalListings: 62,
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'ai-4',
    locality: 'Hinoo',
    city: 'Ranchi',
    propertyType: 'villa',
    avgPrice: 8000000,
    pricePerSqFt: 5333,
    trend: 'stable',
    totalListings: 15,
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'ai-5',
    locality: 'City Center',
    city: 'Dhanbad',
    propertyType: 'independent_house',
    avgPrice: 3600000,
    pricePerSqFt: 2400,
    trend: 'up',
    totalListings: 38,
    updatedAt: new Date('2024-02-28'),
  },
];

export const propertyTypeLabels: Record<string, string> = {
  apartment: 'Apartment',
  independent_house: 'Independent House',
  villa: 'Villa',
  plot: 'Plot',
  agricultural_land: 'Agricultural Land',
  commercial: 'Commercial',
  industrial: 'Industrial',
};

export const amenityLabels: Record<string, string> = {
  parking: 'Parking',
  lift: 'Lift',
  security: '24/7 Security',
  water_supply: 'Water Supply',
  power_backup: 'Power Backup',
  garden: 'Garden',
  gym: 'Gym',
  clubhouse: 'Club House',
  swimming_pool: 'Swimming Pool',
  children_play_area: 'Children Play Area',
  wifi: 'WiFi',
  air_conditioning: 'Air Conditioning',
};

export const facingOptions = [
  { value: 'north', label: 'North' },
  { value: 'south', label: 'South' },
  { value: 'east', label: 'East' },
  { value: 'west', label: 'West' },
  { value: 'northeast', label: 'North-East' },
  { value: 'northwest', label: 'North-West' },
  { value: 'southeast', label: 'South-East' },
  { value: 'southwest', label: 'South-West' },
];

export const ownershipOptions = [
  { value: 'freehold', label: 'Freehold' },
  { value: 'leasehold', label: 'Leasehold' },
  { value: 'cooperative', label: 'Cooperative' },
];

export const landTypeOptions = [
  { value: 'agricultural', label: 'Agricultural' },
  { value: 'residential', label: 'Residential' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'industrial', label: 'Industrial' },
];

export const roadAccessOptions = [
  { value: 'paved', label: 'Paved Road' },
  { value: 'kutcha', label: 'Kutcha Road' },
  { value: 'seasonal', label: 'Seasonal Access' },
];